version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # just to select a compatible runtime
    commands:
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
  build:
    commands:
      - echo Validating Terraform...
      - terraform validate
      - echo Planning Terraform...
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo Applying Terraform...
      - terraform apply -auto-approve tfplan
      - terraform destroy -auto-approve

artifacts:
  files:
    - '**/*'
